name: cat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  file_picker: 8.1.4
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  flutter_markdown: ^0.7.4+3
  cupertino_icons: ^1.0.8
  langchain: ^0.7.7+1
  center_the_widgets: ^1.0.0+3
  langchain_ollama: ^0.3.2+1
  flutter_hooks: ^0.20.5
  syncfusion_flutter_pdf: ^28.1.33
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true

  assets:
    - assets/
